spicy:
  name: spicy
  chainId: 88882
  domainId: 88882
  protocol: ethereum
  rpcUrls:
    - http: https://spicy-rpc.chiliz.com/
arbitrumsepolia:
  name: arbitrumsepolia
  chainId: 421614
  domainId: 421614
  protocol: ethereum
  rpcUrls:
    - http: https://sepolia-rollup.arbitrum.io/rpc
nordektestnet:
  # Required fields:
  chainId: 58875 # Number: Use EIP-155 for EVM chains
  domainId: 58875 # Number: Recommend matching chainId when possible
  name: nordektestnet # String: Unique identifier for the chain, must match key above
  protocol: ethereum # ProtocolType: Ethereum, Sealevel, etc.
  rpcUrls: # Array: List of RPC configs
    # Only http field is required
    - http: https://testnet-rpc.nordekscan.com
 # String: HTTP URL of the RPC endpoint (preferably HTTPS)
      # Others here are optional
      pagination:
        maxBlockRange: 1000 # Number
        maxBlockAge: 1000 # Number
        minBlockNumber: 1000 # Number
      retry:
        maxRequests: 5 # Number
        baseRetryMs: 1000 # Number
  # Optional fields, not required for Hyperlane deployments but useful for apps:
  isTestnet: false # Boolean: Whether the chain is considered a testnet or a mainnet
  blockExplorers: # Array: List of BlockExplorer configs
    # Required fields:
    - name: My Chain Explorer # String: Human-readable name for the explorer
      url: https://testnet-explorer.nordekscan.com/ # String: Base URL for the explorer
      apiUrl: https://testnet-explorer.nordekscan.com/ # String: Base URL for the explorer API

  nativeToken:
    name: Eth # String
    symbol: ETH # String
    decimals: 18 # Number
  displayName: My Chain Name # String: Human-readable name of the chain
  displayNameShort: My Chain # String: A shorter human-readable name
  logoURI: https://mychain.com/logo.png # String: URI to a logo image for the chain
  blocks:
    confirmations: 12 # Number: Blocks to wait before considering a transaction confirmed
    reorgPeriod: 100 # Number: Blocks before a transaction has a near-zero chance of reverting
    estimateBlockTime: 15 # Number: Rough estimate of time per block in seconds
  # transactionOverrides: # Object: Properties to include when forming transaction requests
  # Any tx fields are allowed

# Alternatively, you can extend a core chain config with only fields to be overridden